### ISSUE TITLE
Unnecessary semicolon with "typescript": { "semiColons": "asi" }

### ISSUE THREAD

**Issue by resolritter** [dprint/dprint#229]
**Describe the bug**

Version: dprint v0.4.0-beta2

**Input Code**

```
if ((module as any).hot) {
  (module as any).hot.accept()
}
```

**Expected Output**

Same as the input - it should stay unchanged. ESLint tells me that the semicolon leading to `;(module as any)` is not necessary and complains that the `no-extra-semi` rule is being violated.

**Actual Output**

dprint adds the leading semicolon in `;(module as any)`, although ESLint says it's unnecessary.

```
if ((module as any).hot) {
  ;(module as any).hot.accept()
}
```

**Comment by lazarljubenovic** [comment]
Hmm, I prefer leaving those. If you add a new line above later, you need to insert the `;` below. Makes things messy for the diff, too. If this gets fixed, it should definitely be configurable.

**Comment by dsherret** [comment]
Yeah, this is by design. Although the semi-colon is unnecessary in this context, the reasoning for adding it is to prevent bugs in future code. For example, if you have:

```ts
(module as any).hot.accept()
```

...and add a statement before it...

```ts
testing()
(module as any).hot.accept()
```

...you won't get a bug, which this likely is (this is the same as `testing()(module as any).hot.accept()`).

I recommend disabling any eslint rules related to this as dprint should handle it automatically for you.

**Comment by resolritter** [comment]
For the record, the ESLint rule is called **no-extra-semi**. From what I understood, it's part of the recommended rule set.

https://eslint.org/docs/rules/no-extra-semi

I'll be closing this. Thanks for the quick answer!
