### ISSUE TITLE
stdin-fmt not writing an output

### ISSUE THREAD

**Issue by fjah** [dprint/dprint#279]
Version: 0.7.3

I'm not too sure if this is just me misusing stdin-fmt, but I've also been having an issue since yesterday with dprint-vscode; it just doesn't do anything when I format documents. I do receive error messages when the dprint binary isn't available, so I don't think it's an issue with the extension.

### To reproduce

- Install dprint 0.7.3 on macOS with brew
- Run `dprint stdin-fmt --file-name some_file.rs` and write the content of some_file.rs to stdin
- Receive no output to stdout or any files

Note that this has been happening since 0.7.0, as far as I'm aware, and it applies to all plugins.

**Comment by dsherret** [comment]
@fjah thanks for opening this! The `stdin-fmt` command has been hidden so I've been kind of lazy about it. I opened #281 to improve it.

Two things:

1. `stdin-fmt` now requires a full file path in order to figure out if the file path matches the globs in .dprintrc.json. I will change this back in #281 to not care about the file path then add a new `editor-fmt` for use in editors.
2. There was a bug related to this new functionality and I fixed it in https://github.com/dprint/dprint/commit/5bdd5c896caf05b20040f4289eb8d2c85aa7a0e1

I'm going to close this, but it should be more reliable in 0.7.4 (releasing now). I'll work on #281 for 0.8

**Comment by dsherret** [comment]
This is released now so there's a new `stdin-fmt`.

I've also revamped the editor formatting so it's much better for languages that take a long time to startup (ex. C# due to JIT). It now uses a long running background process. I've outlined it here: https://github.com/dprint/dprint/blob/master/docs/editor-extension-development.md

**Comment by fjah** [comment]
Great! Everything seems to be working okay.

**Comment by dsherret** [comment]
Note that `dprint stdin-fmt --file-name <file-name>` is now `dprint fmt --stdin <file-path/file-name>` in dprint 0.10.0. If you provide a full file path then it will properly include or exclude files from being formatted based on `.dprintrc.json`, but if you don't want that behaviour then provide only a file name.
