### ISSUE TITLE
Programmatic use in Node.js?

### ISSUE THREAD

**Issue by mohsen1** [dprint/dprint#308]
I'm planning to use the JSON formatter in my VSCode plugin. Is it possible to use dprint using purely Node.js? I noticed the npm package was deprecated.

**Comment by dsherret** [comment]
Hey @mohsen1, how's it going? Yeah, it's possible using web assembly, but right now there is only a convenient script for doing it in Deno:

* Script: https://dprint.dev/formatter/v2.ts (node script: https://dprint.dev/formatter/v2.js)
* Docs: https://doc.deno.land/https/dprint.dev/formatter/v2.ts
* Example on this page: https://dprint.dev/plugins/

I believe implementing the `.js` version would work as-is if node supported importing urls. I think I saw them talking about supporting that, but in the meantime (or until I get around to publishing a node package... which I'm kind of lazy to do), you may just want to download that v2.ts file and use it directly.

By the way, I need to open source the license on the JSON plugin. I've had everything locked down, but I believe they want to use the markdown and maybe json plugin in Deno. I'll do that after work and have it adopt MIT.

Also, be aware of this bug with the JSON formatter that I will also fix one day: https://github.com/dprint/dprint-plugin-json/issues/1

**Comment by IWANABETHATGUY** [comment]
webassembly often slower then nodejs binding, better to give another nodejs binding version.

**Comment by mohsen1** [comment]
Well, it is here now:
https://github.com/devongovett/dprint-node

**Comment by dsherret** [comment]
Although dprint-node is interesting, it does not align with dprint's plugin model. I've created a repo at https://github.com/dprint/js-formatter/ along with some plugin packages to make using it a little easier. For example:

```ts
import { createFromBuffer } from "@dprint/formatter";
import { getBuffer } from "@dprint/json";

const formatter = createFromBuffer(getBuffer());

console.log(formatter.formatText("test.json", "{test: 5}"));
```

It should be very portable since it is using web assembly under the hood.

Right now it is lacking the ability to format with multiple different kinds of plugins, so you will have to create several formatters. I will address that in https://github.com/dprint/js-formatter/issues/1
