### ISSUE TITLE
dprint check does not specify which rule was broken

### ISSUE THREAD

**Issue by hb20007** [dprint/dprint#326]
Version: 0.11.0

I was trying out `dprint check` and it seems that it does not indicate which rule is broken.

## Steps to reproduce.

1. Create a new directory and run `dprint init`.
2. Create a `.ts` file.
3. Write the following line in the `.ts` file:

```ts
const testThisIstestThisIstestThisIstestThisIstestThisIstestThisIstestThisIstestThisIsConst = 123;
```

This was the result I got:

![dprint check result](https://user-images.githubusercontent.com/8860322/103139241-eb598d80-46e2-11eb-91c2-c43171751766.png)

## Problem

As you can see, it seems that `dprint check` tries to suggest the change to be made using the green color. However, in this case, it is not clear which rule was broken.

In this example, I am not sure if the line of code broke a line length or a camelCase rule. It would be nice to find out since, in other cases, it might not be so obvious what's wrong with the line of code.

**Comment by dsherret** [comment]
Hey @hb20007, the highlighted parts are the differences. The green highlight shows additions and here it's showing that the formatted text has a newline added to the end of a file. So in this case, the problem is that it's missing a newline at the end of the file.

There's no camel case rules or linting-like rules in dprint-plugin-typescript.

There are some problems with the `dprint check` text diff algorithm and it needs work, but if it ever errors and is non-descriptive you should just be able to run `dprint fmt` on the code to fix any issues.

**Comment by hb20007** [comment]
@dsherret Thanks for the explanation. I will close this issue and make another one with a different example.
