### ISSUE TITLE
dprint check output not very clear?

### ISSUE THREAD

**Issue by hb20007** [dprint/dprint#327]
I'm not sure if it's just me, but it took me a while to understand what the output of `dprint check`  is actually saying.

For example, after adding `"lineWidth": 80` to the rules, I tried running the command on a `.ts` file which contains only the following text:

```ts
const testThisIstestThisIstestThisIstestThisIstestThisIstestThisIstestThisIstestThisIsConst = 123;
```

This was the output I got:

![image](https://user-images.githubusercontent.com/8860322/103139568-3d4fe280-46e6-11eb-91a6-9a0420769990.png)

So, the green area on line 1 is indicates that the line is too long, and the green area below indicates that the file is missing a new line at the end.

I understand that the green highlight shows wrong additions, but, to me, it's confusing and does not indicate the exact problem, especially for the line width rule.

## Question

Perhaps a flag can be added to indicate which rules were broken on which lines? I am only suggesting this if other people agree that it could be helpful. Perhaps others found the output easy to understand when starting out with `dprint`, I don't know.

Also, maybe this is a concern for people with red-green color blindness or for running `dprint check` in a terminal which does not support colors.

**Comment by dsherret** [comment]
@hb20007 there are no explicitly named rules in dprint-plugin-typescript (it does a complete rewrite of the file) and the CLI has no idea about how the plugins work—it only knows the text input and text output so it's doing a text diff on the formatted output vs current text in the file.

In that scenario the input is:

```
1 | const testThisIstestThisIstestThisIstestThisIstestThisIstestThisIstestThisIstestThisIsConst = 123;
```

The formatted output is:

```ts
1 | const testThisIstestThisIstestThisIstestThisIstestThisIstestThisIstestThisIstestThisIsConst =
2 |     123;
3 |
```

So it's showing it added two newlines and then added three spaces in order to do the indent at start of the newline.

> Also, maybe this is a concern for people with red-green color blindness or for running dprint check in a terminal which does not support colors. Not sure.

Do people with red-green colour blindness not modify their terminal colours in order to make red and green distinct? Maybe it's not possible? I'll check with my colour blind coworkers at my last company after christmas (I think one of them is red-green and the other I can't remember).

Perhaps there could be more of a git line diff that just shows + and - rather than inline diffs, but it gets a bit crazy sometimes. I might end up switching to that anyway because the inline diff is a little complicated and I don't have it completely working yet. Would you prefer that?

Example from deno:

![image](https://user-images.githubusercontent.com/1609021/103139891-0dd1b380-46af-11eb-957c-41b6f9c0eca5.png)

**Use Case?**

I'm curious to know what the use case is for knowing exactly why a formatting change was done. What's the use case here?

**Comment by hb20007** [comment]
I hadn't realized that this is the way `dprint check` works. I thought it would analyze the files and give statistics about which rules are broken in which files.

To be honest, I can't see a use case for that functionality. For me, the use case would have been to learn about the rules in the TypeScript / JavaScript plugin. If I can see which rules are broken, I can learn what they do. This makes it easier to identify which rule is breaking in my code and it would be quicker to disable it instead of searching for its name in the documentation. But this is not a very important use case.

> Perhaps there could be more of a git line diff that just shows + and - rather than inline diffs, but it gets a bit crazy sometimes. I might end up switching to that anyway because the inline diff is a little complicated and I don't have it completely working yet. Would you prefer that?

I think it would be nice to have as an option. I see you already have it in mind, so I will close this issue. Thanks for the reply.
