### ISSUE TITLE
Publish plugins on npm

### ISSUE THREAD

**Issue by bpierre** [dprint/dprint#366]
Now that [dprint itself is published on npm](https://github.com/dprint/dprint/commit/40929d978a7ccde7fa0468275a44d0bcb94b71dc) (thank you :pray:), would it be possible to do the same with plugins? e.g. with the [dprint-plugin-typescript](https://www.npmjs.com/package/dprint-plugin-typescript) package. Thanks!

**Comment by dsherret** [comment]
Yes, I have an idea for a quick implementation for this. I will work on it soon.

There is currently https://github.com/devongovett/dprint-node but it doesn't align with the plugin model of dprint. I would prefer to resurect the old dprint-plugin-typescript packages and such in order to have a package per plugin.

By the way, @bpierre, thanks for sponsoring this project! 🙂

**Comment by bpierre** [comment]
Awesome, looking forward to it!

(And thanks to you for dprint :smile:)

**Comment by dsherret** [comment]
This now exists:

```ts
import { createFromBuffer } from "@dprint/formatter";
import { getBuffer } from "@dprint/json";

const formatter = createFromBuffer(getBuffer());

console.log(formatter.formatText("test.json", "{test: 5}"));
```

See here for details https://github.com/dprint/js-formatter

Right now it is lacking the ability to format with multiple different kinds of plugins, so you will have to create several formatters. I will address that in https://github.com/dprint/js-formatter/issues/1
