### ISSUE TITLE
Option to output to stdout

### ISSUE THREAD

**Issue by mitranim** [dprint/dprint#369]
When fmting a single file, there should an option to print to stdout, instead of over-writing the source file. This is required for some editor plugins, such as https://github.com/mitranim/sublime-fmt. There are probably other use cases as well.

There are multiple reasons why editor plugins need stdout. I probably forgot some of the reasons, but here's a few.

Overwriting the file after save is a bad user experience. Even in editors that support auto-reloading on file changes, the content will flash. If the user pressed any keys after saving, there may be a change collision. This generates multiple FS events, which may cause multiple rebuilds in watch-style build systems.

**Comment by mitranim** [comment]
Remembered another reason: the code being fmted _is not always a file_! Sometimes it's an anonymous buffer. You can shove it around via `stdio`. But with the current `dprint` API, it's not possible to format anonymous "files".

**Comment by dsherret** [comment]
Right now there is `dprint fmt --stdin <file-path/file-name/extension>` that I think covers this case. It will take stdin and then output the formatted file text to stdout. If you provide the full file path then it will use the inclusion/exclusion rules from the config file.

I think that covers this scenario, but let me know if not. There is also this, which is slightly faster, but more complex https://github.com/dprint/dprint/blob/main/docs/editor-extension-development.md (currently it doesn't use the lsp, but perhaps that should be done in the future) -- It's especially faster when running certain plugins such as the C# plugin that have a slow initial first run due to JIT and other factors.

**Comment by mitranim** [comment]
Thanks! When looking at this option, I assumed that it uses _only_ stdin, not stdout, and always writes to the provided file. Instead, I expected an option where it takes _no_ file name, and uses its own `cwd` to look for config files. Many similar tools do that, IIRC.

Just tested and it does work! 🙂

**Comment by dsherret** [comment]
> When looking at this option, I assumed that it uses only stdin, not stdout, and always writes to the provided file.

I'll make note to update the description in the CLI.

> For pure stdio, I expected to see an option where it takes no file name, and uses its own cwd to look for config files

It should use its cwd when only a file name or extension is provided. It needs to know the extension at least to figure out what plugin to use to format the file. Best to provide the full file path to get the exclusion/inclusion rules and also there's now more complex rules for figuring out what plugin to use to format (ex. #362).

**Comment by mitranim** [comment]
Thanks for the explanation, now it makes sense. I failed to consider the idiosyncrasies of a multi-language/multi-syntax fmter.
