### ISSUE TITLE
First-class support for .gitignore and .gitattributes

### ISSUE THREAD

**Issue by joscha** [dprint/dprint#378]
In our project, we have a generator that takes a repository state and reads all `.gitignore` and `.gitattributes` files. For `.gitattributes` specifically we're interested in code that is marked autogenerated (see https://github.com/github/linguist/blob/master/docs/overrides.md#generated-code, basically the `linguist-generated` and `linguist-vendored` flags).
It will effectively produce a `dprint.json` file with the `excludes` and `includes` arrays set that extends a hand-written `dprint.base.json` (on a side note: we can't extend the other way round because `includes` and `excludes` are not inherited between configs).

One thing that would be really cool would be if we could
* teach dprint to respect `.gitignore` files as a first-class citizen for `excludes`.
* teach dprint to respect `linguist-generated` and `linguist-vendored` flags from `.gitattributes` as a first-class citizen for `includes` (`includes`, because each of these flags can override to `=false` in a more specific glob pattern)

Thoughts?

**Comment by dsherret** [comment]
The one thing I'm hesitant about with this one is that it introduces a lot of extra complexity and it's [git specific](https://github.com/dprint/dprint/issues/261#issuecomment-670190793).

As pointed out by  @uri-canva, there is a crate that does this though: https://docs.rs/ignore/0.4.18/ignore/

> on a side note: we can't extend the other way round because includes and excludes are not inherited between configs

I think the `includes` and `excludes` inheritance for non-remote files is something I could do soon.

**Comment by dsherret** [comment]
I've been thinking about this more today and with the recent globbing and directory walking changes supporting this would actually be not too bad and wouldn't require an extra lookup (only some extra file reads). Additionally, although I am not very keen on supporting a specific version control system, git is quite prevalent so this will benefit a lot of users.

I can start on it soon. To start, I'll just make it support `.gitignore` files then move on to `.gitattributes`.

**Comment by RubixDev** [comment]
I would suggest adding a setting to the config file called something like `ignoreLists` or `excludeLists` as a list of glob strings. Users can then specify paths to files in the form of `.gitignore` files, or "enable" gitignore support by setting `"ignoreLists": ["**/.gitignore"]`.

For implementation I think the [`Gitignore`](https://docs.rs/ignore/latest/ignore/gitignore/struct.Gitignore.html) struct from the already used `ignore` crate can be used, as it is not specific to git. For each directory a ignore file is in, one `Gitignore` matcher is required, so that globs starting with a `/` inside an ignore file in a subfolder will use that subfolder as their root.

**Comment by joscha** [comment]
nice one @dsherret!
