### ISSUE TITLE
Move per-plugin schema generation to it's respective repositories

### ISSUE THREAD

**Issue by joscha** [dprint/dprint#395]
We have a fork of https://github.com/dprint/dprint-plugin-typescript which adds additional options to the plugin. We'd like to produce an updated schema (e.g. our own variant of https://plugins.dprint.dev/schemas/typescript-v0.json) to be distributed with it.

However there are two issues:

* The schemas for `markdown`, `json`, `typescript` and `toml` are hardcoded in https://github.com/dprint/dprint/blob/main/website/assets/schemas/v0.json (my assumption is that these plugins get extra treatment because they are first-class citizens of https://github.com/dprint :)
* The generation of the per-plugin schemas are not actually happening in each plugin repository, but in the core: https://github.com/dprint/dprint/blob/68507fc007629b415f4e226c4a3371c2edaa9d2e/scripts/build-plugin-schemas.js#L5-L6

Ideas:
* We can extend the auto-generated schema (https://plugins.dprint.dev/schemas/typescript-v0.json) with our own, separate schema that pulls in the original and augments. This *should* work as long as we don't have conflicting options, e.g. out fork does not change existing flags, but only adds new ones. This is true for now and potentially always will be.
* We can move the schema-generation for each `https://plugins.dprint.dev/schemas/<plugin>-v<version>.json` into each of the plugin repositories, potentially by sharing a third-party dep (e.g. a https://github.com/dprint/dprint-plugin-schema-generator) and then attach the schema for each release to the github releases and pick it up from there again when building the dprint.dev website. That way each fork can amend/change the schema as they need to.

related: https://github.com/bcherny/json-schema-to-typescript/issues/402

cc @declanvong

**Comment by dsherret** [comment]
I will move all these slowly into the repositories. They lived in the [plugins](https://github.com/dprint/plugins) repo because previously that served static assets via GitHub pages, but now it's on Deno Deploy so I just created a [redirect to the GitHub release](https://github.com/dprint/plugins/commit/4f2e32e8610ddb4300c6a9fbee00dac82299ceca).

> The schemas for markdown, json, typescript and toml are hardcoded in https://github.com/dprint/dprint/blob/main/website/assets/schemas/v0.json (my assumption is that these plugins get extra treatment because they are first-class citizens of https://github.com/dprint :)

It's due to https://github.com/dprint/dprint/issues/223

I would prefer the main schema to not mention any plugins, but for now this seems to work ok.

> The generation of the per-plugin schemas are not actually happening in each plugin repository, but in the core

Whoa, that script is super old and was from when plugin schemas were generated from the TypeScript code of the plugins (this entire application used to be written in TypeScript instead of Rust). I just deleted it.

Right now the schema is manually maintained and not code generated anymore. It's not too bad, but perhaps there are some discrepancies lurking.

I think you may just want to create your own version of https://github.com/dprint/dprint/blob/main/website/assets/schemas/v0.json and have it point at your own version of the plugins. Or are you wanting to distribute this publicly? In that case the `typescript` schema would have a collision.

I wonder actually if there's a way I could make the dprint vscode plugin pull in the schema so this just all works based on what's in the plugins array. Then I could even remove the "$schema" property in the config file when doing `dprint init`. I've opened https://github.com/dprint/dprint-vscode/issues/15

**Comment by joscha** [comment]
Thanks for the background. Do you want me to close this ticket? It would definitely be good to distribute the schema with each plugin and add the json to the release as well. In out case for example we generate a Typescript definition from the schema as well.

**Comment by dsherret** [comment]
This is now all done.
