### ISSUE TITLE
Playground: optionally display IR and condition resolution for easier debugging

### ISSUE THREAD

**Issue by declanvong** [dprint/dprint#397]
Could also be a separate thing from the Playground, but I think it would be super handy for debugging to be able to just paste my test case in and see what the print items are and how it was parsed, along with how each condition is resolved. 
Currently to try investigate this I'm putting stuff into a test case and debugging it, but it's tedious. Is there a better way? 

Ideally it would be mapped to the AST as well so that it's easier to read (instead of just a single list of print items and conditions), but I suspect that would need a little but more work since except for start/end infos, that metadata doesn't really exist at the moment as far as I'm aware. For now, I think just emitting the print items as they are back to the host would be great. 

This would be really good on top of https://github.com/dprint/dprint/issues/396 as well, I think!

**Comment by declanvong** [comment]
I did see a mention to a graph debugging tool [here](https://github.com/dprint/dprint/issues/354) but I can't seem to find it

**Comment by dsherret** [comment]
@declanvong it would require a separate Wasm build to get the IR and dprint plugins don't necessarily need to be implemented using dprint-core because the Wasm interface doesn't enforce that (it only requires a file path, file text, and config).

Since it's more of a development thing and specific to dprint-core, you can get all this information by adding `(trace)` to the test description then compiling with `--features tracing`. For example: `cargo test --features tracing`. This will give output similar to what's shown here: https://twitter.com/DavidSherret/status/1383218928013299716

Since none of this was documented, I've gone ahead and updated https://github.com/dprint/dprint/tree/main/crates/development#test-specs -- I'll link to that in the plugin development documentation later.

I believe all this should be sufficient, so overall I don't think providing this in the playground is worthwhile.

**Comment by declanvong** [comment]
perfect, thank you!
