### ISSUE TITLE
Support EditorConfig

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#4]
Support editor config?

**Comment by kevgo** [comment]
Using code style from `.editorconfig` would make sense in combination with #413.

**Comment by tomdavidson** [comment]
@kevgo I kinda want this too, but I think DRY is overrated for these things. The enlist-plugin-editorconfig is horribly slow and I ran into some inconsistency what I did not think were worth resolve due to the performance concerns.

What do you think of a 3rd party config sync tool that is a out of band from dprint's (or eslint's) invocation?

**Comment by flying-sheep** [comment]
@dsherret I don’t believe that there’s a measurable impact to load time, did you benchmark this?

I also believe that unifying around a standard that’s respected by all tools is valuable. And many, *many* tools support EditorConfig.

Please reconsider.
