### ISSUE TITLE
Naming convention 

### ISSUE THREAD

**Issue by IWANABETHATGUY** [dprint/dprint#441]
I found it was a little bit ambiguous to use `parser` to naming a format process, for example https://github.com/dprint/dprint-plugin-json/tree/main/src/parser, maybe it would be better to use `printer` instead

**Comment by IWANABETHATGUY** [comment]
I am trying to write a more completed toturial about how to write a language plugin for dprint, so I think it would be better If we could reach an agreement

**Comment by dsherret** [comment]
@IWANABETHATGUY nice! That's great you're writing a tutorial.

If dprint_core::formatting is used to create a dprint plugin, there are two main phases—the IR generation and the printing. In the IR generation phase anything can happen, but it just needs to [create the IR](https://github.com/dprint/dprint/blob/main/docs/overview.md#ir-generation). Then the printing happens by the printer based on the IR that's generated.

You're right that it's a bit ambiguous to use `parser` for the "IR generation" phase because there is also AST parsing. How I view it is that the overall phase is you have the source file text and you parse out the IR from it. A step in that might be parsing an AST or CST to help with that. So "printer" wouldn't work because that's the second phase done [here](https://github.com/dprint/dprint/blob/main/crates/core/src/formatting/printer.rs).

All that said, I've thought about this ambiguity in the past and have been kind of lazy to change it, but I've wanted to do it. I think probably "generation" makes sense. I opened #443 and see an example of its use here https://github.com/dprint/dprint-plugin-json/pull/7

**Comment by IWANABETHATGUY** [comment]
> If dprint_core::formatting is used to create a dprint plugin, there are two main phases—the IR generation and the printing. In the IR generation phase anything can happen, but it just needs to [create the IR](https://github.com/dprint/dprint/blob/main/docs/overview.md#ir-generation). Then the printing happens by the printer based on the IR that's generated.

Thanks!

**Comment by IWANABETHATGUY** [comment]
Hi @dsherret I almostly finish a standard json plugin and passed the test case in your `dprint-json-plugin` repo, I am wonder if you could leave your contact method like discord or others , so we could comunicate conviently
