### ISSUE TITLE
Dprint not discovering yaml files

### ISSUE THREAD

**Issue by quodlibetor** [dprint/dprint#529]
Not sure if I'm holding it wrong, but I figured I would try and format yaml with `yq` using a similar config as I am using for other exec plugins and I can't get dprint to discover any yaml files.

```console
$ dprint --version
dprint 0.27.1
```
```console
$ ls -a frontend/*.yaml(D)
frontend/.prettierrc.yaml  frontend/prettierrc.yaml
$ git s frontend/*.yaml(D)
 M frontend/.prettierrc.yaml
A  frontend/prettierrc.yaml
$ dprint output-file-paths
$
```
Reduced config:
```console
$ cat dprint.json
{
  "includes": ["**/.*.{yml,yaml}"],
  "excludes": ["**/node_modules", "**/.venv", "**/*-lock.json"],
  "exec": {
    "associations": "**/*.{yml,yaml},**/.*.{yml,yaml}",

    "yq": "yq",
    "yq.associations": "**/*.{yml,yaml},**/.*.{yml,yaml}"
  },
  "plugins": [
    "https://plugins.dprint.dev/exec-0.3.0.json@8b9b02f2d5e54597c3644163fe0f2e66452207635edfbf03cc531d627b016158"
  ]
}
```
```console
$ dprint output-resolved-config
{
  "exec": {
    "cacheKey": "0",
    "commands": [
      {
        "executable": "yq",
        "cwd": "...",
        "args": [],
        "stdin": true,
        "associations": "**/*.{yml,yaml},**/.*.{yml,yaml}"
      }
    ],
    "indentWidth": 2,
    "isValid": true,
    "lineWidth": 120,
    "newLineKind": "lf",
    "timeout": 30,
    "useTabs": false
  }
}
```

**Comment by dsherret** [comment]
So the issue here is:

```
"**/*.{yml,yaml},**/.*.{yml,yaml}"
```

If you change that to just...

```
"**/*.{yml,yaml}"
```

...then it should work since that also includes files with a leading period. I think the comma there is being treated as a comma existing in the file path.

I'm not sure the best way to support multiple globs there... I think I should update it to also accept an array of globs similar to how "includes"/"excludes" works instead of only a string.

**Comment by dsherret** [comment]
I opened https://github.com/dprint/dprint/issues/530

Also, arrays in the "associations" property are actually supported so you could write:

```json
"associations": [
  "**/*.{yml,yaml}",
  "**/.*.{yml,yaml}",
]
```

...but it will incorrectly have a json schema error at the moment in vscode (would be fixed by https://github.com/dprint/dprint-vscode/issues/25). For "yq.associations" #530 will add support for arrays there.

That said, again, you can just exclude the second pattern, because the first will catch everything the second pattern matches.

**Comment by quodlibetor** [comment]
Ah, that does indeed work. This evolved from something that looked like `**/*.py,**/*.yml`, which no that I look at it is obviously incorrect, but is still a legal glob pattern.

Changing this to an error reporting possible improvement, I think that if I had received a warning that `**/*.py,**/*.yml` matched no files in my repo I would have immediately known what the problem was -- the py pattern was working previously, so the incremental change shouldn't have been an error.

Thanks!
