### ISSUE TITLE
Don't remove final newline at the end of the file?

### ISSUE THREAD

**Issue by azzamsa** [dprint/dprint#558]
Hi.

Some editor prefer adding new line at the end of the file, such:
- https://github.com/doomemacs/doomemacs/blob/e0385052a8004ec54a402c27357b1352840eb798/lisp/doom-editor.el#L221-L225
- https://github.com/bbatsov/prelude/blob/416ffd3bbfefd551c72017234d3d1be9283fc180/core/prelude-editor.el#L47

How to tell dprint not to remove them? 
[Configuration - dprint - Code Formatter](https://dprint.dev/config/) and [Configuration - Markdown - dprint - Code Formatter](https://dprint.dev/plugins/markdown/config/) doesn't help.

By the way, I think we better enable discussion feature in this repo, this kind of question better suited there.

**Comment by dsherret** [comment]
Are you sure it's dprint removing the newline at the end of the file? Dprint shouldn't do that. Could you provide reproduction steps? You can see here that it adds a newline at the end of the file:

https://dprint.dev/playground/#code/MYewdgziA2CmB00QHMAUBWAlAbiA/language/typescript

> By the way, I think we better enable discussion feature in this repo, this kind of question better suited there.

I don't like discussions because then I have two places to maintain instead of one. Questions are fine for the repo :)

**Comment by azzamsa** [comment]
![image](https://user-images.githubusercontent.com/17734314/186053244-f0b5b967-d3dc-4cc0-9676-01cb37721e37.png)

After inspecting, Yes. It works as my expectation.

> I don't like discussions because then I have two places to check instead of one. Questions are fine for the repo :)

Thanks a lot for dprint, using it ac cross my projects. On the way learning to write dprint for Nushell.
