### ISSUE TITLE
Thread limit

### ISSUE THREAD

**Issue by jamwt** [dprint/dprint#562]
Right now, there's no way (that I've found) to parameterize the number of host CPU threads dprint can utilize. For our company, on a very big CI machine, dprint spawns so many threads that the backing process plugin (prettier) exceeds v8's heap size, and the job fails.

Proposal: some sort of argument to the `dprint` command line that would limit concurrency.

**Comment by dsherret** [comment]
Interesting. Probably something additional could be added to the prettier plugin specifically.

https://github.com/dprint/dprint-plugin-prettier/blob/d67a8720dd6454864b40cf45606f44054d8213d1/src/channel.rs#L71

That said, this would be useful and trivial to add to the CLI. Probably an environment variable since the right number varies per system (DPRINT_MAX_THREADS maybe)

https://github.com/dprint/dprint/blob/63c928bb91824ae73fc8123462ada42b6d6aff84/crates/dprint/src/format.rs#L57

**Comment by dsherret** [comment]
You can set the `DPRINT_MAX_THREADS` environment variable in the latest release (0.32.0).

**Comment by jamwt** [comment]
Thanks so much!
