### ISSUE TITLE
`cargo install-update` doesn't aware of dprint latest version

### ISSUE THREAD

**Issue by azzamsa** [dprint/dprint#565]
Hi.

This is the first time I use `dprint upgrade`. Previously, I always use `cargo install-update -a`.
Now, after using `dprint upgrade`. `cargo install-update` doesn't aware that dprint already the latest version.

```
~
❯ cargo install-update -l
    Updating registry 'https://github.com/rust-lang/crates.io-index'

Package          Installed  Latest   Needs update
cargo-nextest    v0.9.35    v0.9.36  Yes
dprint           v0.31.1    v0.32.1  Yes
broot            v1.14.2    v1.14.2  No
```

```
~
❯ dprint --version
dprint 0.32.1
```

**Comment by dsherret** [comment]
Since the version is managed by cargo in this scenario, there's no way that dprint could tell cargo about this. Actually, in this scenario `dprint upgrade` should error if dprint was installed with cargo and recommend running `cargo install dprint` instead (opened #566).

If you want to use `dprint upgrade`, which is much faster than `cargo install`, then you can uninstall from cargo and install using curl or powershell here: https://dprint.dev/install/

**Comment by azzamsa** [comment]
> If you want to use `dprint upgrade`, which is much faster than `cargo install`, then you can uninstall from cargo and install using curl or powershell here: https://dprint.dev/install/

I will switch to this route then, But I think I will just pick up the binary release, rather than executing the `install.sh`. I don't know how to tell the script (`bin_dir="$dprint_install/bin"`) to install the binary to my custom location.
