### ISSUE TITLE
clarification on how dprint plugins communicate

### ISSUE THREAD

**Issue by tomdavidson** [dprint/dprint#592]
When a file matches multiple plugins, does each plugin have its own filesystem io? I saw the example using flock which suggest as much.

We should expect similar using the exec plugin to run a system cmd  vs running the same cmd outside of dprint? Why would the prettier plugin be faster than calling prettier with the exec plugin?

**Comment by dsherret** [comment]
> When a file matches multiple plugins, does each plugin have its own filesystem io? I saw the example using flock which suggest as much.

No, the CLI reads from the file system and sends the plugins the file text. The Wasm plugins are completely sandboxed and don't have file system access or anything. The process plugins (like the prettier plugin and exec plugin) run in a separate process and have full permissions. They receive the file to format over stdio.

> We should expect similar using the exec plugin to run a system cmd vs running the same cmd outside of dprint? Why would the prettier plugin be faster than calling prettier with the exec plugin?

The exec plugin is slower for certain commands. Basically any command with a slow startup (like prettier or c# because of JIT) will be slower through the exec plugin, but some commands are fast with it (like rustfmt. I've been meaning to deprecate the dprint [rustfmt plugin](https://dprint.dev/plugins/rustfmt/) until they allow compiling on Wasm again actually because I've found it performs very well in the exec plugin). dprint-plugin-prettier should be faster because it doesn't launch prettier over and over again, but instead keeps the process alive while receiving formatting requests. That said, you can try out both and see which one works faster.

Also, thanks for the sponsorship. I appreciate it!

**Comment by tomdavidson** [comment]
Thanks! I did try to figure this out via looking at the code but came up short. One follow-up:  Does the CLI read the file, pass it the plugin via stdio, then write the file for each plugin match? Or does the CLI only read and write the file once, regardless of how many plugins process it?

**Comment by dsherret** [comment]
> Does the CLI read the file, pass it the plugin via stdio, then write the file for each plugin match? Or does the CLI only read and write the file once, regardless of how many plugins process it?

The CLI reads the file, passes it to the plugin via stdio, the plugin formats it, then the plugin sends the result back via stdio. There could actually be multiple plugins that format the file, so the CLI might send it to another plugin at this point. When it's all done, if the file has changed then it will write it to the file system. So the CLI only reads and writes the file once.

**Comment by tomdavidson** [comment]
Perfect and thank you!
