### ISSUE TITLE
error resolving plugin

### ISSUE THREAD

**Issue by delta1** [dprint/dprint#656]
hey not sure what changed, getting this error message: 

```
Error resolving plugin https://plugins.dprint.dev/rustfmt-0.6.1.exe-plugin@99b89a0599fd3a63e597e03436862157901f3facae2f0c2fbd0b9f656cdbc2a5: Error downloading https://plugins.dprint.dev/rustfmt-0.6.1.exe-plugin@99b89a0599fd3a63e597e03436862157901f3facae2f0c2fbd0b9f656cdbc2a5 - 404 Not Found
```

**Comment by dsherret** [comment]
@delta1 sorry, the dprint CLI stopped supporting `.exe-plugin` (I should have have temporarily had a better error message). Also, I deprecated the rustfmt plugin until they support building for wasm again (https://github.com/dprint/dprint-plugin-rustfmt/) because it's better to have dprint just orchestrate calling `rustfmt`.

For upgrading rustfmt, you can use the following configuration:

```
{
  // ...etc...
  "exec": {
    "associations": "**/*.{rs}",

    "rustfmt": "rustfmt --edition 2021",
    "rustfmt.associations": "**/*.rs"
  },
  "includes": [
    "**/*.{rs}"
  ],
  "plugins": [
    "https://plugins.dprint.dev/exec-0.3.5.json@d687dda57be0fe9a0088ccdaefa5147649ff24127d8b3ea227536c68ee7abeab"
  ]
}
```

**Comment by delta1** [comment]
Thanks @dsherret!
