### ISSUE TITLE
could not parse Dockerfile from version 0.46

### ISSUE THREAD

**Issue by su-bob** [dprint/dprint#854]
Version: 0.46.1

<pre>
Run npx dprint fmt
npm WARN exec The following package was not found and will be installed: dprint@0.4[6](https://github.com/foo/bar/actions/runs/9248092520/job/25437964047#step:7:7).1
Compiling https://plugins.dprint.dev/dockerfile-0.3.0.wasm
Error formatting /home/runner/work/foo/bar/base.Dockerfile. Message: could not parse Dockerfile:  --> 1:1
  |
1 | ﻿# stage, restore:␊
  | ^---
  |
  = expected dockerfile
Error formatting /home/runner/work/foo/bar/Dockerfile/match.Dockerfile. Message: could not parse Dockerfile:  --> 1:1
  |
1 | ﻿ARG IMAGE_BASE␊
  | ^---
  |
  = expected dockerfile
Error formatting /home/runner/work/foo/bar/Dockerfile/schedule.Dockerfile. Message: could not parse Dockerfile:  --> 1:1
  |
1 | ﻿ARG IMAGE_BASE␊
  | ^---
  |
  = expected dockerfile
Had 3 errors formatting.
Error: Process completed with exit code 1.
</pre>

I replaced my project name to 'foo/bar'. 

It works well with dprint@0.45.1. 
There is a problem from today. (dprint@0.46.1 deployed some hours ago)

https://github.com/dprint/dprint-plugin-dockerfile
dprint-plugin-dockerfile have no changes from 4 month ago. 

I'm testing if the problem is fixed by fixing the dprint version to 0.45.1.

**Comment by dsherret** [comment]
My guess is https://github.com/dprint/dprint/pull/844

Does the file start with a byte order mark? I'll have to update that plugin to handle this scenario it seems.

**Comment by su-bob** [comment]
Oh, you're right. there was a BOM in that files. BOOOM

**Comment by dsherret** [comment]
This is now fixed in all the plugins that were previously causing an issue. Please run the following in your projects:

```
dprint config update && dprint fmt
```

Very sorry about the hassle here! It was an oversight as I meant to look into whether the plugins would handle it and then forgot.

Also, I'm unsure of the impact of this BOM change... hopefully it doesn't break too many people. At least it's for the better in the long run to leave the BOM handling to the plugins as the dprint CLI now only works with bytes and not strings.

Final point: a change in some of the plugins was to now strip the BOM. It seems like something dprint-plugin-typescript has done for a while and some other plugins so I doubt this is an issue, but if someone really needs to keep BOMs for a good reason, then please explain why and I'll look into adding config to force BOMs.
