### ISSUE TITLE
Rust code formatter for rust-analzyer

### ISSUE THREAD

**Issue by matklad** [dprint/dprint#86]
Hey, author of [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) here. Long term, rust-analyzer needs a code formatter, and I like the IR approach you are taking, so I thought I'll dump some of my thoughts on formatting in case they are useful.

To be clear, this is in no way a feature request or something like that, feel free to ignore completely! :)

In rust-analyzer, we sometimes have to synthesize new code and insert such generated code into something written by a user (mostly for refactorings). Our syntax trees represent whitespaces and comments explicitly, so we can represent properly formatted and indented code. However, just manually producing formatted code is a huge pain, so the ideal solution for authors of refactorings is to build code with bad formatting, pipe it through the formatter and insert the good version.

The specifics of IDE places some constraits on the formatting tool however (which are not met by rustfmt). Specifically:

1. The formatter has to handle incomplete code reasonably, as in IDE use-case almost all code is half-writtn and contain syntax errors. For example, the formatter should somehow reasonably format the following code

```rust
fn example() {
    let x = if bar
    foo()
}
```

which is parsed into the following syntax tree:

```text
FN_DEF@[0; 45)
  FN_KW@[0; 2) "fn"
  WHITESPACE@[2; 3) " "
  NAME@[3; 10)
    IDENT@[3; 10) "example"
  PARAM_LIST@[10; 12)
    L_PAREN@[10; 11) "("
    R_PAREN@[11; 12) ")"
  WHITESPACE@[12; 13) " "
  BLOCK_EXPR@[13; 45)
    BLOCK@[13; 45)
      L_CURLY@[13; 14) "{"
      WHITESPACE@[14; 19) "\n    "
      LET_STMT@[19; 33)
        LET_KW@[19; 22) "let"
        WHITESPACE@[22; 23) " "
        BIND_PAT@[23; 24)
          NAME@[23; 24)
            IDENT@[23; 24) "x"
        WHITESPACE@[24; 25) " "
        EQ@[25; 26) "="
        WHITESPACE@[26; 27) " "
        IF_EXPR@[27; 33)
          IF_KW@[27; 29) "if"
          WHITESPACE@[29; 30) " "
          CONDITION@[30; 33)
            PATH_EXPR@[30; 33)
              PATH@[30; 33)
                PATH_SEGMENT@[30; 33)
                  NAME_REF@[30; 33)
                    IDENT@[30; 33) "bar"
      WHITESPACE@[33; 38) "\n    "
      CALL_EXPR@[38; 43)
        PATH_EXPR@[38; 41)
          PATH@[38; 41)
            PATH_SEGMENT@[38; 41)
              NAME_REF@[38; 41)
                IDENT@[38; 41) "foo"
        ARG_LIST@[41; 43)
          L_PAREN@[41; 42) "("
          R_PAREN@[42; 43) ")"
      WHITESPACE@[43; 44) "\n"
      R_CURLY@[44; 45) "}"
```

2. The formatter should be able to reformat only part of the code. Specifically, during refactorings we want to reformat only the parts touched by refactorings, and freeze the rest. For example, if "extract variable" transforms

```rust
fn foo() {
    bar(1+1)
}
```

into

```rust
fn foo() {
    let var = 1+1;
    bar(var)
}
```

we want the formatter to handle spaces around `=` and indentation of the whole let, but we do **not** want it to "fix" spaces around `+`, as that's what the user originally written, and we should not "touch" that (but note that might have to re-indent it anyway)

3. (This is mostly subjective, and I am willing to concede this constraint) In general, formatting should not mess with what the user has written. So, it should introduce spaces around operators and re-indent stuff, but, in general, it should not decide how to break large expressions into multiple lines. 

So, this all leads me to the idea that rust-analyzer will be better off with a rule-based formatter, where you specify the rules like "a `+` should always be surrounded by one space on each side", and let the formatting engine to figure out the necessary whitespace changes to satisfy all the rules. Possible alternatives are pretty-printers, where the formatter mostly disregards the original formatting and just pretty-prints the code in one true way (rustfmt works like this) or cost-optimization formatters, where there's a certain "pretiness" metric, and the formatter literary searches for the best layout that optimizes this metric (dartfmt works like this I think).

Your IR approach resembles in some aspects what I have in mind for rust-analyzer. In particular, rules like "insert spaces around `+`" or "if function call is multiline, there should be a \n before )" could be expressed with conditionals. The main differnece is that I am thinking about tree-shaped, and not linear IR, for formatting, but perhaps *lowering* to a sequence migth be a better approach.

Overall, I am super excited about dprint, and would love to study its approach in more details :) Thanks for building it!

**Comment by dsherret** [comment]
Hey @matklad, really interesting post and it's neat to see where rust-analyzer is going. One of my coworkers was talking about it the other day commenting on how much he likes it 🙂

> Our syntax trees represent whitespaces and comments explicitly, so we can represent properly formatted and indented code.

Having comments in the tree is good design decision and I'm familiar with the problem... the TS compiler does not at least have comments in the tree, so in [ts-morph](https://github.com/dsherret/ts-morph) (tool for doing automated refactorings in TypeScript) I am in the process of injecting those in so that people don't accidentally stamp them out and can insert around them (right now comments are not stored in the AST at all):

![image](https://user-images.githubusercontent.com/1609021/73804012-71e64300-4790-11ea-924d-defec4253e05.png)

Regarding whitespaces, I've been thinking a bit just now and I think you're probably right to have them in there. If they're expected, then those nodes can easily be ignored if necessary when navigating the tree and in situations where they would be nice to have then they are available (the benefit of having them for those few cases outweighs the minor annoyance in other cases). Actually, I think an annoying part about many compilers is that if you transform the AST then reprint it, it will change the code quite a lot... with your setup someone could transform the AST then a full print could happen that wouldn't change the formatting. Interesting!

> However, just manually producing formatted code is a huge pain, so the ideal solution for authors of refactorings is to build code with bad formatting, pipe it through the formatter and insert the good version.

Do they write text changes (ex. change text at pos 10-20 to "other code"), then rust-analyzer incrementally parses out the text to format? Or do they transform the AST that then gets printed/formatted (I'm guessing this)? Or something else?

> The formatter has to handle incomplete code reasonably, as in IDE use-case almost all code is half-written and contain syntax errors.

Yeah, I know many compilers handle that by exploding out the possibilities the tree can have. For formatting the entire file with an expanded tree I would view the problem of code formatting to be the same except that there are more possibilities—in dprint's case it's an IR generation challenge (not an IR printing one).

By the way, that's a nice looking tree 🙂. I'm holding myself back from going too off topic by talking more about it haha

> 2. The formatter should be able to reformat only part of the code. Specifically, during refactorings we want to reformat only the parts touched by refactorings, and freeze the rest.

I guess the way to do that would be to know what parts in the old code map to what in the new code (perhaps the nodes are tracked?). The example you gave kind of sounds like something the refactoring author should think about and that could be helped by making it easy for them to apply the formatting selectively. Maybe not though—I'm just thinking out loud.

> Your IR approach resembles in some aspects what I have in mind for rust-analyzer. In particular, rules like "insert spaces around +" or "if function call is multiline, there should be a \n before )" could be expressed with conditionals. The main difference is that I am thinking about tree-shaped, and not linear IR, for formatting, but perhaps lowering to a sequence might be a better approach.

I see you read [this document](https://github.com/dsherret/dprint/blob/master/docs/overview.md) 🙂. I have to go through and refine a few things in the printer itself and there's been a few signals added, but that document allows you to get the gist of it.

Yeah, the whole condition system continues to blow me away with how powerful it is and I'm loving it so far. I think it would be a nightmare to maintain this project without something at least like it. The "info" nodes are a huge part of it too and how they can be placed in the future (further down in the IR/file) to help resolve conditions in the past has been extremely useful. It's also possible to help resolve conditions by looking at the result of other condition IR nodes (ex. "was there an open brace at the start of this IfStatement? If so print this close brace").

> or cost-optimization formatters, where there's a certain "pretiness" metric, and the formatter literary searches for the best layout that optimizes this metric (dartfmt works like this I think).

That's interesting. I've never thought about that! I'll have to look into dartfmt.

**Formatting Partial Files**

I think the main hard part about formatting partial files is that there's two possible sources for getting information about where the surrounding code is:

1. It could be printed by the IR printer, in which case the information about those positions needs to come from resolving those IR "info" nodes...
2. Or it could be position information from the AST.

This is an IR generation problem though and the code creating the conditions would need to solve it. It definitely would make it more complex, but it might not be too bad.

> The main differnece is that I am thinking about tree-shaped, and not linear IR, for formatting, but perhaps lowering to a sequence migth be a better approach.

What advantage were you thinking for a tree-shaped IR? I'm thinking that might be an implementation detail, but I'm curious about that.

> Overall, I am super excited about dprint, and would love to study its approach in more details :) Thanks for building it!

Thanks! Yeah, I'd like to go through and refine a few things, but I don't think I'm going to be changing the basic idea of conditions and infos. I think you could probably benefit from a similar concept and perhaps even using dprint's core would be beneficial as a starting point. When I find the time I should write about how the printer works under the hood because I think it's quite interesting and maybe there's some concepts you could take from it.

**Comment by DevinR528** [comment]
> What advantage were you thinking for a tree-shaped IR? I'm thinking that might be an implementation detail, but I'm curious about that.

It seems to me you can have more semantic meaning/context embedded into each node when you know child from parent. The way the rules engine works so far is by defining relationships ex. add space/newline/indent after comma but only when the parent of the comma is `ARRAY_EXPR`.
I really like the way you solved the indent anchoring by just keeping track of where you are in the IR text as far as `newlineGroup` and `indentGroup`, we don't keep track we use the parent anchor to calculate the level of indent on demand.

Although now that I sit and try to think of examples of times you specifically need a parent and not just iterating backwards from the current token I'm stumped.

Great project and a really cool use of rust and wasm!! Always nice to see people using rust.

**Comment by matklad** [comment]
> If they're expected, then those nodes can easily be ignored if necessary when navigating the tree and in situations where they would be nice to have then they are available (the benefit of having them for those few cases outweighs the minor annoyance in other cases)

I would say that whitespace create literary no annoyance for the typical compiler code, there's no "skip if whitespace" calls in rust analyzer anywhere outside of the parts which are specifically dealing with whitespace. Though, that maybe because our AST is not a traditional bunch of transparent ADTs which you can match through, but rather a more opaque data structure with explicit accessors for children. 

The two main problems with explicit whitespace are:

* you kinda need more memory to store them. Roughly, half of the nodes in the tree are tokens, and half of the tokens are whitespace, so its something like 25% of the whole tree (haven't done actual measurements though, the actual difference might be bigger or smaller, there are many higher-order factors like node interning in play here). That's not a problem for rust-analyzer, because we explicitly don't optimize syntax trees to be as fast/compact as possible. Rather, we try to get rid of them as soon as possible, and lower to a compact, simplified, arena allocated AST. 

* I am not sure what is the *right* way to store comments. rust-analyzer (and IntelliJ) goes with an obvious solution of just storing them in there, like any other token. Swift and Roslyn do something more elaborate though: they explicitly partition tokens into meaningful (keywords, idents, operators), and trivial (comments and whitespace). Only meaningful tokens are stored in the tree, but each meaningful token also holds preceeding and trailing trivia. The benefit of the latter approach is that it's easier to implement for traditional ADT based ASTs (as you don't have to add explicit trivia all other the place). [This doc](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/syntax.md#dealing-with-trivia) has more info on the topic

>with your setup someone could transform the AST then a full print could happen that wouldn't change the formatting. Interesting!

Moreover, you can parse *any* string into an AST and print it back. Our parser is resilient to errors, so `parse . to_string` is a **total** identity function. 


>Do they write text changes (ex. change text at pos 10-20 to "other code"), then rust-analyzer incrementally parses out the text to format? Or do they transform the AST that then gets printed/formatted (I'm guessing this)? Or something else?

I am not sure we are entirely understanding each other here, so let me try to elaborate. First of all, "pipe it through the formatter" is how this is *supposed* to work, but we don't have formatter, so at the moment we just manually try to insert reasonable whitespace, and oftentimes the result is less then ideal. 

Because the syntax tree is immutable, the general process is that we take an existing node apart, assemble a new node from old and new pieces, and then manufacture a text edit which replaces an old node with a new one. [This wold be a nice, short example](https://github.com/rust-analyzer/rust-analyzer/blob/8d0f7da2f5f2ae1dc5711005f08fde0007da165b/crates/ra_assists/src/assists/replace_if_let_with_match.rs#L11-L67). So, I think the API I want to see from the formatter is

```rust
fn reformat(
  // root node to reformat
  root: Node,
  // descendants of the `root` which were originally written by the user and which should not be generally touched, except for adjusting the overall indent
  exclude: Vec<Node>,
  // for the full generality, as we might want to replace some bits of user-written code, an overrides for the `exclude` parameter
  include: Vec<Node>,
) -> Node
```

Also, to be precise, rust-analyzer can not itself mutate source files, it can only send diffs to the client who owns original source code. So, the final output of each refactoring is a diff. But, internally, each refactoring just computes the desired syntax tree, and the actual text edit is computed by diffing original and desirable trees. 

>What advantage were you thinking for a tree-shaped IR?

TBH, the main advantage for me is that's what IntelliJ is using, so it's more familiar to me and also proven that it works (which does not mean that this is the best approach). Specifically, the formatting tree is pretty close in shape to the syntax tree, and so conditions are naturally expressed in term of the shape of the syntax tree. For example, this

https://github.com/intellij-rust/intellij-rust/blob/779ab34da9e165ab02876b52ff666804b7d58c19/src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt#L44

adds either a space or a \n after `,` in the list of fields or enum variants, depending on whether the parent is multiline. Note how this does not need a separate ast -> IR step (I think this is `parse` in dprint terminology), where you separately lower structs and separately lower enums. Rather, this is a single pattern which "magically" works for both cases. 

> I'm holding myself back from going too off topic by talking more about it haha

BTW, feel free to discuss more general things in our Zulip: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0.

**Comment by dsherret** [comment]
Sorry, been pretty busy working on a few things especially with the TS 3.8 release coming up. If either of you are ever in Toronto then let me know as I'd love to sit down and talk about all of this in depth 🙂

@matklad thanks so much for explaining all of that. It's super interesting to know the reasons for why you made certain decisions and to know these details.

Yeah, the TS compiler takes a similar approach to Roslyn except everything needs to be reparsed out afterwards. I want to create my own c# formatter using Roslyn one day (even though dotnet format exists) and I'll be able to use the underlying dprint Rust IR printer to do that... so IR generation in c#, then printing in Rust.

Also, thanks for linking to those rust-analyzer docs. I will read through them soon!

**Tree-shaped vs flat IR**

A key part about dprint is that the generated IR is never manipulated and ideally it shouldn't be inspected while generating IR—the IR should only look at the result of "resolved" conditions and infos. In other words, it should only ask "what was the result of that condition?" and "where did that info end up when printed?". For that reason the IR can be stored in whatever ends up being the fastest approach for the printer.

What I've found is fastest is to only have nodes in the IR that point at whatever the next node to print is. For example: 

```
Node { Signal::StartIndent } -> Node { "Some text" } -> Node { Signal::FinishIndent } -> ...`
```

Rather than an IR object like`Indent { items: ["Some text"] }`).

---

Getting more into the weeds and I will probably do a terrible job explaining this, for "Rc paths" which is a path of IR found in multiple places in the IR (behind an `Rc<T>`... example to follow) and conditions it maintains a "next node stack" which is a stack of nodes it will use once it reaches the end of a path... that is, once a node doesn't have a next node.

So for example, given the following:

```
// `with_indent` is a helper function that surrounds the `items` with Signal::StartIndent and Signal::FinishIndent.
// In this case `items` is an "rc path" as it's used in multiple places.

Node { "some text" } -> Node { Condition { true_path: with_indent(items), false_path: items } } -> Node { "more text" } -> ...
```

It will visit the `"some text"` node, then at the condition it pushes the `"more text"` node onto the "next node stack". Then resolves the condition. Let's assume true, so it visits `Signal::StartIndent` then pushes the `Signal::FinishIndent` node onto the next node stack, then visits whatever is in `items`, after that it finds no next node so pops the `Signal::FinishIndent` node off the stack, handles it, see's there's no next node, then pops off the `"more text"` node off the stack and keeps going.

An important part of printing is that it needs to create "save points" which are states in printing that the printer can return to once it figures out more information (ex. it's gone over the line width and wants to return to a possible newline point). So to create a save point it needs to know things like what the node to return to is, what's in the next node stack, what's the current indentation level, etc. But creating those save points can be more expensive if there's a lot of stuff in the "next node stack", so that's mainly why the IR is implemented as flat as possible.

Anyway, it's kind of hard to explain this all without explaining a whole lot of other stuff. I should write all this into a document in the repo with visuals soon.

---

I'd like to know more about the approach in IntelliJ, is there an overview somewhere? JetBrains makes solid products.

**Non-string-based printer**

The IR printer doesn't actually work with strings and only works with a trait that provides a length. From there it generates a second simple IR (I call those ["write items"](https://github.com/dsherret/dprint/blob/e0ed66b826611abeaa5c5416b6147cf3d27a1c87/packages/rust-core/src/write_items.rs#L5)), and from the final write items it constructs the final string. I abstracted away the string in order to support [JsStrings](https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.JsString.html) from WASM.

@matklad anyway, I think it wouldn't be hard at all to maybe add something to the printer to help make it easier to construct an AST from the printer's output. That's what would be ideal for you right? Even if you wouldn't end up using it, I think it would be a neat scenario to support.

Also, I'll hop on zulip once things die down for me and I have some time :)

> I think this is parse in dprint terminology

Yeah, I call the IR generation step "parsing" in the code right now and prefix all the functions with "parse". I'm not sure if that's appropriate, but can't think of anything better. Let me know if you have any suggestions.

**Comment by matklad** [comment]
> If either of you are ever in Toronto 

Noted! :)

>I should write all this into a document in the repo with visuals soon.

That would be useful!

https://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/code_formatting.html

>I'd like to know more about the approach in IntelliJ, is there an overview somewhere? JetBrains makes solid products.

Sadly, the amount of docs there is sparse. These two pages describe how to implement your custom formatter (ie, they describe formatting DSL/gen_ir/parse phase):

* https://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/code_formatting.html
* https://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/formatter.html

I don't think docs for the actual formatting engine that applies the rules exists. There's source code though: https://github.com/JetBrains/intellij-community/tree/5c3f54c486856d513c33088a76c7805d312d7ae7/platform/lang-impl/src/com/intellij/formatting.

This looks like an [entry point](https://github.com/JetBrains/intellij-community/blob/5c3f54c486856d513c33088a76c7805d312d7ae7/platform/lang-impl/src/com/intellij/formatting/FormatterImpl.java#L275-L298).

**Comment by dsherret** [comment]
The dprint IR is interesting and very flexible, but I'm not sure if it's the best choice for languages like Rust which have lots of expressions. Probably needs a bit more improvement in that regard, which I don't have time for atm, so going to close this one :)
